name: Build LaTeX documents
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Get commit message
        id: commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Get commit SHA
        id: commit_sha
        run: echo "::set-output name=sha::${GITHUB_SHA::8}"

      - name: Get current date and time
        id: current_datetime
        run: echo "::set-output name=datetime::$(date +'%Y-%m-%d-%H-%M-%S')"
      - name: CreateRelease
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.current_datetime.outputs.datetime }}-${{ github.run_number }}
          release_name: Release-${{ steps.current_datetime.outputs.datetime }}-${{ github.run_number }}
          body: |
            New release created from commit: ${{ steps.commit_sha.outputs.sha }}
          draft: false
          prerelease: false

      - name: Compile Math LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: math.tex
          latexmk_use_xelatex: true
      - name: Upload Math PDF
        id: upload-math-pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./math.pdf
          asset_name: math.pdf
          asset_content_type: application/pdf

      - name: Compile CS LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cs.tex
          latexmk_use_xelatex: true
      - name: Upload CS PDF
        id: upload-cs-pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cs.pdf
          asset_name: cs.pdf
          asset_content_type: application/pdf